version: 2
updates:
  # Node.js 依赖更新
  - package-ecosystem: "npm"
    directory: "/WarpGo-manager"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Dabuguoni"
    assignees:
      - "Dabuguoni"
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"

  # Rust 依赖更新
  - package-ecosystem: "cargo"
    directory: "/WarpGo-manager/src-tauri"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Dabuguoni"
    assignees:
      - "Dabuguoni"
    commit-message:
      prefix: "cargo"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"

  # GitHub Actions 更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "Dabuguoni"
    assignees:
      - "Dabuguoni"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
