name: 持续集成

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  basic-check:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: 检查项目结构
      run: |
        echo "=== 项目根目录 ==="
        ls -la
        echo "=== WarpGo-manager 目录 ==="
        ls -la WarpGo-manager/
        echo "=== package.json 内容 ==="
        cat WarpGo-manager/package.json

    - name: 安装前端依赖
      working-directory: WarpGo-manager
      run: npm install

    - name: 检查依赖安装
      working-directory: WarpGo-manager
      run: |
        echo "=== node_modules 检查 ==="
        ls -la node_modules/ | head -10
        echo "=== package-lock.json 检查 ==="
        ls -la package-lock.json


