name: 持续集成

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: 安装 Rust
      uses: dtolnay/rust-toolchain@stable

    - name: 安装 Linux 依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev

    - name: 安装前端依赖
      working-directory: WarpGo-manager
      run: npm install

    - name: 前端构建检查
      working-directory: WarpGo-manager
      run: npm run build

    - name: Rust 编译检查
      working-directory: WarpGo-manager/src-tauri
      run: cargo check


